### ISSUE TITLE
Unable to View A League I know is Public

### ISSUE THREAD

**Issue by jcrande** [kiernann/fflr#44]
I am attempting to use the ESPN Fantasy API for a school project. I am positive the league I am trying to access is public and I am also member of said league. I have tried this league along with the deafault leagues and nothing is working. I am getting the error telling me that I am not authorized to view this league:

Error: ESPN Fantasy API request failed [401]
You are not authorized to view this League.

```r
library(fflr)
packageVersion("fflr")
ffl_id(leagueId = "415461308")
league_info()
league_teams()
```

Thank you

**Comment by kiernann** [comment]
What does `packageVersion("fflr")` return?
