### ISSUE TITLE
league_members() incorrectly reports FALSE for isLeagueManager

### ISSUE THREAD

**Issue by carolbeau** [kiernann/fflr#45]
The league with ID 372045 is a public league with Format:League Manager.  For this type of league, the creator is the league manager (LM).  source: https://support.espn.com/hc/en-us/articles/360012530592-League-Manager-Powers 

For this league, the member with displayName="beaudotdu" is the creator/LM.  However, the league_members() function incorrectly reports isLeagueManager='FALSE' for this record (and indeed for all records). I think isLeagueManager should return "TRUE" for the record with displayName="beaudotdu".

``` r
library("fflr")
ffl_id(leagueId = "372045")
#> Temporarily set `fflr.leagueId` option to 372045
#> [1] "372045"
league_members()
#> # A tibble: 12 × 3
#>    displayName       memberId                               isLeagueManager
#>    <chr>             <chr>                                  <lgl>          
#>  1 emawrica          {0DA013D1-4DC1-4505-B436-762D517A8EEF} FALSE          
#>  2 Brothel           {12191A2A-F88F-4305-B5FB-6562A3868C95} FALSE          
#>  3 thinroof          {275B71EB-1CDB-4773-B1D2-DDA75719FFEC} FALSE          
#>  4 beaudotdu         {39120363-0EC5-4AFA-BC61-B917B9E0B42F} FALSE          
#>  5 Hoskins 1967      {39A66B77-BD4C-431A-BFD0-2E105A7D0FDA} FALSE          
#>  6 Djreisner         {4F4ACA96-86ED-49F6-8ACA-9686EDB9F667} FALSE          
#>  7 cmdeans           {5F453EB7-92A8-45C6-8AD5-278C8128A83E} FALSE          
#>  8 danktuary         {690CD6BF-0A10-42B1-8467-827865AC5CD8} FALSE          
#>  9 maxkerney         {727174CB-06CF-4144-801C-F0B7F73A9D1A} FALSE          
#> 10 ESPNfan0310132266 {76153B6B-C633-4F03-9703-8C738749BEF8} FALSE          
#> 11 rmdean5513396     {A68B1C77-41BA-41B5-97D8-F7739A296B25} FALSE          
#> 12 eaderoui          {B9683870-B962-4E77-8033-F8E3F28CEF2E} FALSE
```

<sup>Created on 2023-12-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kiernann** [comment]
Unfortunately this appears to be a bug in the way the ESPN API is handling your league settings. 

The data coming from ESPN is `FALSE` for each league member, it's nothing that is being changed by the R package interface.

``` r
library(jsonlite)
dat <- fromJSON(
  txt = "https://fantasy.espn.com/apis/v3/games/ffl/seasons/2023/segments/0/leagues/372045?view=mNav"
)
dat$members$isLeagueManager
#>  [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
```

<sup>Created on 2023-12-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
